/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:17d007df-93eb-474d-870e-9af712779bb3",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_2JqmnoVrI",
    "aws_user_pools_web_client_id": "31oi5hni0jpcp9i331kkvt418s",
    "oauth": {}
};


export default awsmobile;
